import pandas as pd
from Шульгин.helpers.helpers import get_profile

df_progress = pd.read_excel('helpers/09.04 ИС УРФУ (1).xlsx')
df_progress['Leader ID'] = df_progress['Leader ID'].astype(str)

examus = ["Ponkratova_E@chtz.ru",
"standrey74@gmail.com",
"i.matveeva_@mail.ru",
"Paklinala@yandex.ru",
"winxksuna@mail.ru",
"akintsevaav@susu.ru",
"svdanilova@lenta.ru",
"i.matveeva_@mail.ru",
"voytovichga@mail.ru",
"ntb@chtz.ru",
"orlov_ud@bk.ru",
"winxksuna@mail.ru",
"IrinaVishnevskaya1209@mail.ru",
"akisseleva94@gmail.com",
"taneeya@mail.ru",
"513557@mail.ru",
"punda59@mail.ru",
"unatali@bk.ru",
"varlamova_zn@mail.ru",
"12345_686@mail.ru",
"natasha_m92@mail.ru",
"perevozchikovya@mail.ru",
"kuzan41@mail.ru",
"lazareva17@list.ru",
"glimuko@rambler.ru",
"verpetrova@yandex.ru",
"fial2@yandex.ru",
"alefkov@yandex.ru",
"missis.dasha1997@mail.ru",
"csukbcp2011@gmail.com",
"elnik01@mail.ru",
"eln.kostikova@gmail.com",
"akhmadullina.yul@yandex.ru",
"chernNP@mail.ru",
"winxksuna@mail.ru",
"natach_1966@mail.ru",
"Schulgina@yandex.ru",
"kartasheval@susu.ru",
"varlamova_zn@mail.ru",
"griga_ira@list.ru",
"dvinin1981@mail.ru",
"svetlana_minina@mail.ru",
"kartasheval@susu.ru",
"susmarin@mail.ru",
"anatali06-78@mail.ru",
"mem229@mail.ru",
"standartelm@mail.ru",
"nina_777s@mail.ru",
"ignatieva_e@chtz.ru",
"sasha-tingaev@rambler.ru",
"fleyteng_m@chtz.ru",
"lora-proyaeva@mail.ru",
"gerasimovam@susu.ru",
"bearandfly@gmail.com",
"nadezhda-sh86@ya.ru",
"_degi_@mail.ru",
"ysav19@mail.ru",
"vinantov@mail.ru",
"dmzah@csu.ru",
"lulunchik1@mail.ru",
"serj.chernyshov@mail.ru",
"baskakova_t@cntz.ru",
"ilona-law@ya.ru",
"o.temnikova@rambler.ru",
"karasev.alexei2012@yandex.ru",
"sunny_song@mail.ru",
"natali_v70@mail.ru",
"sega.kozh@mail.ru",
"uliay030183@yandex.ru",
"a.fedchenkov@yandex.com",
"surinaaa@susu.ru",
"demianenkots@susu.ru",
"SVLos777@mail.ru",
"vlad00767@mail.ru",
"econ3812@gmail.com",
"rolly55581@gmail.com",
"valeriya131@yandex.ru",
"vnb@bk.ru",
"veritas45@mail.ru",
"suharev_a@chtz.ru",
"alena5757@mail.ru",
"gollaiav@susu.ru",
"kardvv@mail.ru",
"pav-2010@mail.ru",
"u.malygina@bk.ru",
"larissavik@inbox.ru",
"tugovaekaterina1997@gmail.com",
"kovalchuklidia@yandex.ru",
"ps.noc.m@gmail.com",
"surinva@susu.ru",
"stashkevich_dary@mail.ru",
"9080818113@mail.ru",
"zzhanbek@yandex.ru",
"otimofeeva83@mail.ru",
"v.sedakova@ugmk.com",
"al.schtefan2011@yandex.ru",
"kurgans2@mail.ru",
"isupovjurij@rambler.ru",
"andreeva_sv81@mail.ru"]

df = pd.read_excel('завершившие.xlsx')

lol = []
for index, row in df.iterrows():
    lol.append(row['email'].lower())

for x in examus:
    if x.lower() not in lol:
        print(x)